name: Release and publish

on: workflow_dispatch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: read
      actions: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Set Git user
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
      - name: Set semantic version
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        with:
          arguments: final --stacktrace
      - name: Build JAR
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        with:
          arguments: jar --stacktrace
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }} JAR
          path: build/libs/${{ github.event.repository.name }}-*.jar
      - name: Publish to GitHub Packages
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        with:
          arguments: publish --stacktrace
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
